(function(){
 "use strict";
 const S={user:{},master:{projects:[],employees:[],vehicles:[],branches:[]},work:[],regie:[],workEvidence:[],regieEvidence:[],workSignatures:{},regieSignatures:{},workServiceDrawing:null,drawing:null,drawingContext:null,photoQueue:[],lastView:"dashboard",sync:{pending:0,failed:0,conflicts:0,running:false}};
 const MANUAL_PROJECT="__manual__",UNIT_OPTIONS=["Stk","m","lfm","m²","m³","kg","h","PA","Set","VE"];
 const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID?.()||Date.now()+"-"+Math.random(),today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
 const fmt=n=>new Intl.NumberFormat("de-AT",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0),euro=n=>new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR"}).format(Number(n)||0),dateLabel=d=>d?new Intl.DateTimeFormat("de-AT",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(d+"T12:00:00")):"";
 function node(tag,cls,txt){const n=document.createElement(tag);if(tag==="button")n.type="button";if(cls)n.className=cls;if(txt!=null)n.textContent=txt;return n}function toast(t){$("toast").textContent=t;$("toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("toast").classList.remove("show"),2300)}
 async function init(){const auth=await HasplAuth.ready;if(!auth?.ok)return;S.user=auth.user||{};await RegieDB.open();bind();S.master=await RegieAPI.load().catch(()=>({projects:[],employees:[],vehicles:[],branches:[]}));fillProjects();RegieLV.init();applyPermissions();await reload();showView("dashboard");registerSW();updateOnline();await RegieSync.initialize(S.user)}
 function bind(){
  document.querySelectorAll("button:not([type])").forEach(b=>b.type="button");
  document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));
  $("homeBtn").onclick=()=>showView("dashboard");$("userBtn").onclick=showUser;
  $("newWorkBtn").onclick=$("workAddBtn").onclick=newWork;
  $("continueWorkBtn").onclick=()=>{const r=S.work.find(x=>x.date===today());r?editWork(r.id):newWork()};
  $("newRegieBtn").onclick=$("regieAddBtn").onclick=newRegie;$("openLvBtn").onclick=()=>showView("lv");
  $("refreshMasterBtn").onclick=refreshMaster;$("workBackBtn").onclick=()=>showView("daily");$("regieBackBtn").onclick=()=>showView("regie");
  $("addWorkerBtn").onclick=()=>addWorker();$("addWorkMaterialBtn").onclick=()=>addWorkMaterial();
  $("addLaborBtn").onclick=()=>addLabor();$("addRequestMaterialBtn").onclick=()=>addRequestMaterial();
  $("workForm").onsubmit=saveWork;$("regieForm").onsubmit=saveRegie;
  $("deleteWorkBtn").onclick=deleteWork;$("deleteRegieBtn").onclick=deleteRegie;
  $("printWorkBtn").onclick=()=>printCurrent("work");$("printRegieBtn").onclick=()=>printCurrent("regie");
  $("syncBadge").onclick=()=>RegieSync.run({manual:true});
  $("workForm").addEventListener("input",()=>saveState("work",true));$("regieForm").addEventListener("input",()=>saveState("regie",true));
  $("workProject").onchange=()=>projectChanged("work");$("regieProject").onchange=()=>projectChanged("regie");
  document.querySelectorAll('[name="reportKind"]').forEach(i=>i.onchange=updateWorkHeading);
  $("workLvPosition").onchange=()=>lvSelected("work");$("regieLvPosition").onchange=()=>lvSelected("regie");
  $("workManualCostCenter").oninput=()=>$("workCostCenter").value=$("workManualCostCenter").value;$("regieManualCostCenter").oninput=()=>$("regieCostCenter").value=$("regieManualCostCenter").value;
  ["workFilterSearch","workFilterProject","workFilterKind","workFilterCompletion","workFilterSync","workFilterFrom","workFilterTo","workFilterCreator","regieFilterSearch","regieFilterProject","regieFilterSync","regieFilterFrom","regieFilterTo","regieFilterCreator"].forEach(id=>$(id).addEventListener(id.includes("Search")?"input":"change",renderLists));
  $("resetWorkFiltersBtn").onclick=()=>resetFilters("work");$("resetRegieFiltersBtn").onclick=()=>resetFilters("regie");
  document.querySelectorAll(".travelRow input").forEach(i=>i.addEventListener("input",calcWorkHours));
  bindEvidence("work");bindEvidence("regie");bindSignatures();bindDrawing();bindWorkServiceDrawing();
  window.addEventListener("regie-lv-updated",e=>{if(e.detail.projectId===$("workProject").value)fillLvSelect("work",e.detail.positions);if(e.detail.projectId===$("regieProject").value)fillLvSelect("regie",e.detail.positions)});
  window.addEventListener("regie-data-updated",reload);
  window.addEventListener("regie-sync-status",e=>{S.sync=e.detail;updateOnline();reload()});
  window.addEventListener("online",()=>{updateOnline();RegieSync.run()});window.addEventListener("offline",updateOnline);
  $("conflictServerBtn").onclick=()=>resolveCurrentConflict("server");$("conflictLocalBtn").onclick=()=>resolveCurrentConflict("local");$("conflictCancelBtn").onclick=()=>$("conflictDialog").close();
  window.addEventListener("haspl-open-report",e=>{const {id,type}=e.detail||{};if(type==="work")editWork(id);else if(type==="regie-request")editRegie(id)});
  window.addEventListener("haspl-show-conflict",e=>{if(e.detail)showConflict(e.detail)});
 }
 function showView(v){if(v!=="editor"&&v!=="regie-editor")S.lastView=v;document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id===`view-${v}`));document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v||(v==="editor"&&b.dataset.view==="daily")||(v==="regie-editor"&&b.dataset.view==="regie")));window.scrollTo({top:0,behavior:"auto"});if(v==="dashboard"||v==="daily"||v==="regie")renderLists();if(v==="lv"){$("lvProject").value=$("workProject").value||$("regieProject").value||"";RegieLV.loadProject($("lvProject").value)}}
 function updateOnline(){const on=navigator.onLine,badge=$("syncBadge");let text="Offline";if(on&&S.sync.running)text="Synchronisiert …";else if(on&&S.sync.conflicts)text=`${S.sync.conflicts} Konflikt${S.sync.conflicts===1?"":"e"}`;else if(on&&S.sync.failed)text=`${S.sync.failed} Sync-Fehler`;else if(on&&S.sync.pending)text=`${S.sync.pending} ausständig`;else if(on)text="✓ Synchronisiert";badge.textContent=text;badge.classList.toggle("offline",!on);badge.classList.toggle("warning",!!(S.sync.failed||S.sync.conflicts));badge.title=on?"Zum erneuten Synchronisieren antippen":"Änderungen bleiben sicher lokal gespeichert"}
 function saveState(type,dirty){const n=$(type==="work"?"workSaveState":"regieSaveState");n.textContent=dirty?"Ungespeicherte Änderungen":"Lokal gespeichert";n.style.color=dirty?"var(--amber)":"var(--green)"}
 function fillProjects(){const projects=S.master.projects.slice().sort((a,b)=>String(a.name||"").localeCompare(String(b.name||""),"de"));["workProject","regieProject","lvProject"].forEach(id=>{const s=$(id),val=s.value;s.replaceChildren(new Option("Baustelle wählen",""));if(id!=="lvProject")s.add(new Option("✎ Baustelle frei eingeben",MANUAL_PROJECT));projects.forEach(p=>s.add(new Option(`${p.number?`${p.number} · `:""}${p.name}`,p.id)));s.value=val});["workFilterProject","regieFilterProject"].forEach(id=>{const s=$(id),val=s.value;s.replaceChildren(new Option("Alle Baustellen",""),new Option("Frei eingegebene Baustellen",MANUAL_PROJECT));projects.forEach(p=>s.add(new Option(`${p.number?`${p.number} · `:""}${p.name}`,p.id)));s.value=val})}
 async function refreshMaster(){try{S.master=await RegieAPI.refresh();fillProjects();await RegieSync.pullRemote();toast("Stammdaten und Berichte aktualisiert")}catch(_){toast("Aktualisierung derzeit nicht möglich")}}
 async function reload(){const all=await RegieDB.getAll("reports");S.work=all.filter(r=>!r.deletedAt&&r.type==="work").sort(sortDate);S.regie=all.filter(r=>!r.deletedAt&&r.type==="regie-request").sort(sortDate);renderLists()}function sortDate(a,b){return String(b.date||b.periodFrom||b.updatedAt).localeCompare(String(a.date||a.periodFrom||a.updatedAt))}
 function project(id){return S.master.projects.find(p=>p.id===id)}function projectName(id,fallback="Baustelle"){return project(id)?.name||fallback}function branchForProject(p){return S.master.branches?.find(b=>b.id===p?.branchId)}
 function workKind(report){return report?.kinds?.regie?"regie":report?.kinds?.daily?"daily":report?.kinds?.material?"material":""}
 function workTitle(report){return {regie:"Regiebericht",daily:"Tagesbericht",material:"Materialbericht"}[workKind(report)]||"Arbeitsbericht"}
 function updateWorkHeading(){const kind=document.querySelector('[name="reportKind"]:checked')?.value||"";$('workEditorTitle').textContent=kind?`Neuer ${{regie:"Regiebericht",daily:"Tagesbericht",material:"Materialbericht"}[kind]}`:"Neuer Arbeitsbericht"}
 function isAdmin(){return ["admin","development"].includes(String(S.user.role||"").toLowerCase())}
 function isOwn(report){return isAdmin()||!!S.user.id&&report.createdBy===S.user.id}
 function creatorName(report){if(report.createdByName)return report.createdByName;if(report.createdBy===S.user.id)return [S.user.firstName,S.user.lastName].filter(Boolean).join(" ")||S.user.username||"Ich";const employee=S.master.employees.find(e=>e.linkedUserId===report.createdBy);return employee?.fullName||employee?.name||report.createdBy||"Unbekannt"}
 function resetFilters(type){const ids=type==="work"?["workFilterSearch","workFilterProject","workFilterKind","workFilterCompletion","workFilterSync","workFilterFrom","workFilterTo","workFilterCreator"]:["regieFilterSearch","regieFilterProject","regieFilterSync","regieFilterFrom","regieFilterTo","regieFilterCreator"];ids.forEach(id=>$(id).value="");renderLists()}
 function matchesSearch(report,value){if(!value)return true;const text=[report.reportNo,report.requestNo,report.projectName,report.services,report.client,report.orderNo,report.remark,report.remarks,creatorName(report)].join(" ").toLocaleLowerCase("de");return text.includes(value.toLocaleLowerCase("de").trim())}
 function filterWork(report){const projectFilter=$("workFilterProject").value,date=report.date||"",sync=report.conflict?"conflict":report.syncStatus||"local";return matchesSearch(report,$("workFilterSearch").value)&&(!projectFilter||(projectFilter===MANUAL_PROJECT?!!report.manualProject:report.projectId===projectFilter))&&(!$("workFilterKind").value||workKind(report)===$("workFilterKind").value)&&(!$("workFilterCompletion").value||report.completion===$("workFilterCompletion").value)&&(!$("workFilterSync").value||sync===$("workFilterSync").value)&&(!$("workFilterFrom").value||date>=$("workFilterFrom").value)&&(!$("workFilterTo").value||date<=$("workFilterTo").value)&&(!$("workFilterCreator").value||report.createdBy===$("workFilterCreator").value)}
 function filterRegie(report){const projectFilter=$("regieFilterProject").value,date=report.periodFrom||report.createdAt?.slice(0,10)||"",sync=report.conflict?"conflict":report.syncStatus||"local";return matchesSearch(report,$("regieFilterSearch").value)&&(!projectFilter||(projectFilter===MANUAL_PROJECT?!!report.manualProject:report.projectId===projectFilter))&&(!$("regieFilterSync").value||sync===$("regieFilterSync").value)&&(!$("regieFilterFrom").value||date>=$("regieFilterFrom").value)&&(!$("regieFilterTo").value||date<=$("regieFilterTo").value)&&(!$("regieFilterCreator").value||report.createdBy===$("regieFilterCreator").value)}
 function fillCreatorFilters(rows){[["workFilterCreator",S.work],["regieFilterCreator",S.regie]].forEach(([id,list])=>{const select=$(id),value=select.value,creators=new Map();list.forEach(r=>{if(r.createdBy)creators.set(r.createdBy,creatorName(r))});select.replaceChildren(new Option("Alle Ersteller",""));[...creators].sort((a,b)=>a[1].localeCompare(b[1],"de")).forEach(([key,name])=>select.add(new Option(name,key)));select.value=value});$("workCreatorFilterWrap").hidden=!isAdmin();$("regieCreatorFilterWrap").hidden=!isAdmin()}
 function renderLists(){const visibleWork=S.work.filter(isOwn),visibleRegie=S.regie.filter(isOwn);fillCreatorFilters([...visibleWork,...visibleRegie]);const filteredWork=visibleWork.filter(filterWork),filteredRegie=visibleRegie.filter(filterRegie),recent=[...visibleWork,...visibleRegie].sort(sortDate).slice(0,6);renderList($("recentReports"),recent);renderList($("workList"),filteredWork);renderList($("regieList"),filteredRegie);$("workResultCount").textContent=`${filteredWork.length}/${visibleWork.length}`;$("regieResultCount").textContent=`${filteredRegie.length}/${visibleRegie.length}`;const tr=visibleWork.find(r=>r.date===today());$("todayReportState").textContent=tr?`${projectName(tr.projectId,tr.projectName)} · ${fmt(workTotal(tr))} h`:"Noch nicht angelegt";$("todayTitle").textContent=new Intl.DateTimeFormat("de-AT",{weekday:"long",day:"2-digit",month:"long",year:"numeric"}).format(new Date())}
 function renderList(box,rows){box.replaceChildren();box.classList.toggle("emptyState",!rows.length);if(!rows.length){box.textContent="Keine passenden Berichte gefunden.";return}rows.forEach(r=>{const art=node("article","reportItem"),isWork=r.type==="work",title=node("b",null,`${isWork?workTitle(r):"Regieanforderung"} ${r.reportNo||r.requestNo||""} · ${projectName(r.projectId,r.projectName)}`),creator=isAdmin()&&r.createdBy?` · ${creatorName(r)}`:"",meta=node("small",null,isWork?`${dateLabel(r.date)} · ${fmt(workTotal(r))} h · ${(r.evidence||[]).length} Fotos/Skizzen${creator}`:`${dateLabel(r.periodFrom)} · ${euro(requestTotal(r))} · ${(r.evidence||[]).length} Fotos/Skizzen${creator}`),status=node("span",`reportSync ${r.syncStatus||"local"}`,syncLabel(r)),actions=node("div","reportActions"),open=node("button","secondary","Öffnen");open.onclick=()=>isWork?editWork(r.id):editRegie(r.id);actions.append(open);if(allowed(isWork?"regieapp.work_reports.export":"regieapp.requests.export")){const print=node("button","secondary","PDF erstellen");print.onclick=async()=>{try{await RegiePrint.print(r,S.master);toast("PDF wurde erstellt")}catch(error){console.error(error);toast("PDF konnte nicht erstellt werden")}};actions.append(print)}if(r.conflict){const conflict=node("button","danger","Konflikt lösen");conflict.onclick=()=>showConflict(r);actions.append(conflict)}art.append(title,meta,status,actions);box.append(art)})}
 function syncLabel(r){return r.conflict?"⚠ Konflikt":r.syncStatus==="synced"?"✓ Synchronisiert":r.syncStatus==="error"?"⚠ Sync-Fehler":r.syncStatus==="pending"?"↻ Synchronisierung ausständig":"Lokal gespeichert"}
 function manualIds(type){return type==="work"?{panel:"workManualProject",name:"workManualName",address:"workManualAddress",costCenter:"workManualCostCenter",clientAddress:"workManualClientAddress",contact:"workManualContact",contactInfo:"workManualContactInfo",siteManager:"workManualSiteManager",projectManager:"workManualProjectManager",internalOrder:"workManualInternalOrder"}:{panel:"regieManualProject",name:"regieManualName",address:"regieManualAddress",costCenter:"regieManualCostCenter",client:"regieManualClient",clientAddress:"regieManualClientAddress",contact:"regieManualContact",contactInfo:"regieManualContactInfo",siteManager:"regieManualSiteManager",projectManager:"regieManualProjectManager",internalOrder:"regieManualInternalOrder"}}
 function showManualProject(type,show){const ids=manualIds(type);$(ids.panel).hidden=!show;$(ids.name).required=show}
 function fillManualProject(type,data={}){const ids=manualIds(type);Object.entries(ids).forEach(([key,id])=>{if(key!=="panel"&&$(id))$(id).value=data[key]||""});if(type==="work"){$("workClient").value=data.client||$("workClient").value||"";$("workOrderNo").value=data.customerOrderNumber||$("workOrderNo").value||""}}
 function collectManualProject(type){const ids=manualIds(type),data={};Object.entries(ids).forEach(([key,id])=>{if(key!=="panel"&&$(id))data[key]=$(id).value.trim()});if(type==="work"){data.client=$("workClient").value.trim();data.customerOrderNumber=$("workOrderNo").value.trim()}return data}
 function emptyForm(id){$(id).reset()}
 function newWork(){emptyForm("workForm");showManualProject("work",false);$("workId").value=uid();$("workDate").value=today();$("workCostCenter").value="";$("workerRows").replaceChildren();$("workMaterialRows").replaceChildren();S.workEvidence=[];S.workSignatures={};S.workServiceDrawing=null;addWorker(S.user.employeeId?{employeeId:S.user.employeeId}:{});addWorkMaterial();renderEvidence("work");renderSignatures("work");renderWorkServiceDrawing();$("deleteWorkBtn").hidden=true;$("workEditorTitle").textContent="Neuer Arbeitsbericht";saveState("work",true);showView("editor")}
 async function editWork(id){const r=S.work.find(x=>x.id===id);if(!r)return;emptyForm("workForm");const manual=!!r.manualProject;$("workId").value=r.id;$("workProject").value=manual?MANUAL_PROJECT:r.projectId||"";showManualProject("work",manual);if(manual)fillManualProject("work",r.manualProject);$("workDate").value=r.date||today();$("workCostCenter").value=r.costCenterName||branchForProject(project(r.projectId))?.name||r.manualProject?.costCenter||"";$("workClient").value=r.client||r.manualProject?.client||"";$("workOrderNo").value=r.orderNo||r.manualProject?.customerOrderNumber||"";$("workReportNo").value=r.reportNo||"";$("kindRegie").checked=!!r.kinds?.regie;$("kindDaily").checked=!!r.kinds?.daily;$("kindMaterial").checked=!!r.kinds?.material;$("workServices").value=r.services||"";$("workRemark").value=r.remark||"";if(r.completion)document.querySelector(`[name=completion][value="${r.completion}"]`)?.click();$("workerRows").replaceChildren();(r.workers||[]).forEach(addWorker);if(!r.workers?.length)addWorker();$("workMaterialRows").replaceChildren();await projectChanged("work",r.lvPosition);(r.materials||[]).forEach(addWorkMaterial);if(!r.materials?.length)addWorkMaterial();document.querySelectorAll(".travelRow input").forEach(i=>i.value=r.travel?.[i.dataset.day]||"");S.workEvidence=structuredClone(r.evidence||[]);S.workSignatures=structuredClone(r.signatures||{});S.workServiceDrawing=structuredClone(r.serviceDrawing||null);renderEvidence("work");renderSignatures("work");renderWorkServiceDrawing();$("deleteWorkBtn").hidden=!allowed("regieapp.work_reports.delete");$("workEditorTitle").textContent=`${workTitle(r)} ${r.reportNo||dateLabel(r.date)}`;saveState("work",false);showView("editor");calcWorkHours()}
 function addWorker(d={}){const row=node("div","timeMatrix workerTimeRow"),picker=node("div","employeePicker"),sel=document.createElement("select"),custom=input(d.employeeName||"","Name frei eingeben"),employees=S.master.employees.slice().sort((a,b)=>String(a.name||"").localeCompare(String(b.name||""),"de"));custom.className="employeeCustom";sel.append(new Option("Mitarbeiter aus Portal wählen",""),new Option("✎ Mitarbeiter frei eingeben",MANUAL_PROJECT),...employees.map(e=>new Option(e.name,e.id)));const known=S.master.employees.some(e=>e.id===d.employeeId);sel.value=known?d.employeeId:(d.employeeName?MANUAL_PROJECT:"");custom.hidden=sel.value!==MANUAL_PROJECT;sel.onchange=()=>{custom.hidden=sel.value!==MANUAL_PROJECT;if(!custom.hidden)custom.focus()};picker.append(sel,custom);row.append(picker);["mo","di","mi","do","fr","sa","p50","p100"].forEach(k=>{const i=document.createElement("input");i.type="number";i.step="0.25";i.min="0";i.value=d[k]??"";i.dataset.key=k;i.oninput=calcWorkHours;row.append(i)});const total=node("b","rowTotal","0,00"),del=node("button","rowRemove","×");del.onclick=()=>{row.remove();calcWorkHours()};row.append(total,del);$("workerRows").append(row);calcWorkHours()}
 function materialPositions(type){const projectId=$(type==="work"?"workProject":"regieProject").value;return projectId&&projectId!==MANUAL_PROJECT?RegieLV.getPositions():[]}
 function normalizeLvSearch(value){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("de-AT")}
 function populateMaterialLvPicker(picker,positions,query="",selected=""){const select=picker.querySelector(".materialLv"),needle=normalizeLvSearch(query.trim()),needleCompact=needle.replace(/[^a-z0-9]/g,""),current=selected||select.value||"";select.replaceChildren(new Option("Freie Eingabe / keine LV-Position",""));const matches=needle?positions.filter(p=>{const haystack=normalizeLvSearch(`${p.pos||""} ${p.text||""} ${p.lg||""}`);return haystack.includes(needle)||(needleCompact&&haystack.replace(/[^a-z0-9]/g,"").includes(needleCompact))}).slice(0,100):[];const currentPosition=positions.find(p=>p.pos===current);if(current&&!currentPosition)select.add(new Option(`Im Bericht gespeichert: ${current}`,current));else if(currentPosition&&!matches.some(p=>p.pos===current))select.add(new Option(`Aktuell: ${currentPosition.pos} · ${currentPosition.text}`,currentPosition.pos));matches.forEach(p=>select.add(new Option(`${p.pos} · ${p.text}`,p.pos)));if(needle&&!matches.length){const empty=new Option("Keine passende LV-Position gefunden","__no_match__");empty.disabled=true;select.add(empty)}else if(!needle&&positions.length){const hint=new Option("Zum Suchen oben Text eingeben","__search_hint__");hint.disabled=true;select.add(hint)}select.value=current||""}
 function makeLvPicker(selected="",type="work"){const picker=node("div","lvMaterialPicker"),search=input("","LV-Position oder Text suchen","search"),select=document.createElement("select");search.className="materialLvSearch";select.className="materialLv";picker.dataset.reportType=type;picker.append(search,select);const positions=materialPositions(type);populateMaterialLvPicker(picker,positions,"",selected);search.oninput=()=>populateMaterialLvPicker(picker,materialPositions(type),search.value,select.value);search.onsearch=search.oninput;return picker}
 function makeUnitPicker(value=""){value=value==="Psch"?"PA":value;const wrap=node("div","unitPicker"),sel=document.createElement("select"),custom=input("","Einheit eingeben");sel.className="unitSelect";custom.className="unitCustom";sel.add(new Option("Einheit wählen",""));UNIT_OPTIONS.forEach(u=>sel.add(new Option(u,u)));sel.add(new Option("Andere Einheit …","__custom__"));const known=UNIT_OPTIONS.includes(value);sel.value=known?value:(value?"__custom__":"");custom.value=!known?value:"";custom.hidden=sel.value!=="__custom__";sel.onchange=()=>{custom.hidden=sel.value!=="__custom__";if(!custom.hidden)custom.focus()};wrap.append(sel,custom);return wrap}
 function setUnitPicker(row,value=""){value=value==="Psch"?"PA":value;const sel=row.querySelector(".unitSelect"),custom=row.querySelector(".unitCustom");if(UNIT_OPTIONS.includes(value)){sel.value=value;custom.value="";custom.hidden=true}else if(value){sel.value="__custom__";custom.value=value;custom.hidden=false}else{sel.value="";custom.value="";custom.hidden=true}}
 function getUnit(row){const sel=row.querySelector(".unitSelect");return sel.value==="__custom__"?row.querySelector(".unitCustom").value.trim():sel.value}
 function materialLvChanged(row,isRequest=false){const pos=row.querySelector(".materialLv").value,p=RegieLV.getPositions().find(x=>x.pos===pos);if(!p)return;const name=row.querySelector(isRequest?".materialArticle":".materialName");name.value=`${p.pos} · ${p.text}`;setUnitPicker(row,p.unit||"");if(isRequest&&p.ep!=null)row.querySelector(".materialRate").value=Number(p.ep)||"";if(isRequest)calcRequest()}
 function addWorkMaterial(d={}){const row=node("div","materialRow workMaterialRow"),lvPicker=makeLvPicker(d.lvPosition,"work"),lv=lvPicker.querySelector(".materialLv"),name=input(d.name,"Material / Artikel"),q=input(d.quantity,"Menge","number"),unit=makeUnitPicker(d.unit);name.className="materialName";q.className="materialQuantity";q.step="0.01";lv.onchange=()=>materialLvChanged(row,false);row.append(label("LV-Unterposition suchen oder frei eingeben",lvPicker),label("Bezeichnung",name),label("Menge",q),label("Einheit",unit),remove(row));$("workMaterialRows").append(row)}
 function calcWorkHours(){let sum=0;document.querySelectorAll(".workerTimeRow").forEach(r=>{const val=[...r.querySelectorAll("input[data-key]")].reduce((s,i)=>s+(Number(i.value)||0),0);r.querySelector(".rowTotal").textContent=fmt(val);sum+=val});const travel=[...document.querySelectorAll(".travelRow input")].reduce((s,i)=>s+(Number(i.value)||0),0);$("travelTotal").textContent=fmt(travel);$("workHoursTotal").textContent=`${fmt(sum)} h`}
 function collectWorkers(){return [...document.querySelectorAll(".workerTimeRow")].map(r=>{const sel=r.querySelector("select"),manual=sel.value===MANUAL_PROJECT,values={employeeId:manual?"":sel.value};r.querySelectorAll("input[data-key]").forEach(i=>values[i.dataset.key]=Number(i.value)||0);values.employeeName=manual?r.querySelector(".employeeCustom").value.trim():S.master.employees.find(e=>e.id===values.employeeId)?.name||"";values.manual=manual;return values}).filter(x=>x.employeeId||x.employeeName||["mo","di","mi","do","fr","sa","p50","p100"].some(k=>x[k]))}
 function collectTravel(){const o={};document.querySelectorAll(".travelRow input").forEach(i=>o[i.dataset.day]=Number(i.value)||0);return o}function collectWorkMaterials(){return [...document.querySelectorAll(".workMaterialRow")].map(r=>({lvPosition:r.querySelector(".materialLv").value,name:r.querySelector(".materialName").value.trim(),quantity:Number(r.querySelector(".materialQuantity").value)||0,unit:getUnit(r)})).filter(x=>x.lvPosition||x.name||x.quantity)}
 function showWarning(title,text){$("warningDialogTitle").textContent=title;$("warningDialogText").textContent=text;$("warningDialog").showModal()}
 async function saveWork(e){e.preventDefault();const selectedKind=document.querySelector('[name="reportKind"]:checked')?.value||"",completion=document.querySelector('[name="completion"]:checked')?.value||"";if(!selectedKind){showWarning("Berichtstyp auswählen","Bitte vor dem Speichern genau einen Berichtstyp wählen: Regiebericht, Tagesbericht oder Materialbericht.");return}if(!completion){showWarning("Abschlussstatus auswählen","Bitte Teilfertig, Baustelle abgeschlossen oder Arbeiten offen auswählen.");return}if(!$("workServices").value.trim()&&!S.workServiceDrawing?.preview){showWarning("Arbeitsleistung fehlt","Bitte die ausgeführte Leistung als Text eingeben oder mit dem Stift festhalten.");return}if(!$("workForm").reportValidity())return;const id=$("workId").value||uid(),old=await RegieDB.get("reports",id),manual=$("workProject").value===MANUAL_PROJECT,p=manual?null:project($("workProject").value),b=branchForProject(p),manualProject=manual?collectManualProject("work"):null,r={...old,id,type:"work",date:$("workDate").value,projectId:p?.id||"",projectName:p?.name||manualProject?.name||old?.projectName||"",branchId:p?.branchId||"",costCenterName:manualProject?.costCenter||b?.name||"",client:$("workClient").value.trim(),orderNo:$("workOrderNo").value.trim(),reportNo:$("workReportNo").value.trim(),lvPosition:$("workLvPosition").value,kinds:{regie:selectedKind==="regie",daily:selectedKind==="daily",material:selectedKind==="material"},services:$("workServices").value.trim(),serviceDrawing:structuredClone(S.workServiceDrawing),workers:collectWorkers(),travel:collectTravel(),materials:collectWorkMaterials(),remark:$("workRemark").value.trim(),completion,evidence:structuredClone(S.workEvidence),signatures:structuredClone(S.workSignatures),manualProject,createdBy:old?.createdBy||S.user.id||"local-user",createdByName:old?.createdByName||[S.user.firstName,S.user.lastName].filter(Boolean).join(" ")||S.user.username||"Lokaler Benutzer",createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),syncStatus:manual?"local":"pending",conflict:old?.conflict||null};await RegieDB.put("reports",r);if(!manual)await RegieSync.queueReport(r);await reload();$("deleteWorkBtn").hidden=!allowed("regieapp.work_reports.delete");$("workEditorTitle").textContent=`${workTitle(r)} ${r.reportNo||dateLabel(r.date)}`;saveState("work",false);toast(manual?`${workTitle(r)} lokal gespeichert`:navigator.onLine?`${workTitle(r)} gespeichert – Synchronisierung läuft`:`${workTitle(r)} sicher offline gespeichert`)}
 async function deleteWork(){const id=$("workId").value,r=await RegieDB.get("reports",id);if(r&&confirm("Arbeitsbericht wirklich löschen?")){await RegieSync.queueDelete(r);await reload();showView("daily")}}
 function workTotal(r){return (r.workers||[]).reduce((s,w)=>s+["mo","di","mi","do","fr","sa","p50","p100"].reduce((x,k)=>x+(Number(w[k])||0),0),0)}
 function newRegie(){emptyForm("regieForm");showManualProject("regie",false);$("regieId").value=uid();$("periodFrom").value=today();$("regieCostCenter").value="";$("laborRows").replaceChildren();$("requestMaterialRows").replaceChildren();S.regieEvidence=[];S.regieSignatures={};const employee=S.master.employees.find(e=>e.id===S.user.employeeId);addLabor(employee?.billingCategory?{category:employee.billingCategory}:{});addRequestMaterial();renderEvidence("regie");renderSignatures("regie");$("deleteRegieBtn").hidden=true;$("regieEditorTitle").textContent="Neue Regieanforderung";saveState("regie",true);showView("regie-editor")}
 async function editRegie(id){const r=S.regie.find(x=>x.id===id);if(!r)return;emptyForm("regieForm");const manual=!!r.manualProject;$("regieId").value=r.id;$("regieProject").value=manual?MANUAL_PROJECT:r.projectId||"";showManualProject("regie",manual);if(manual)fillManualProject("regie",r.manualProject);$("regieCostCenter").value=r.costCenterName||branchForProject(project(r.projectId))?.name||r.manualProject?.costCenter||"";$("requestNo").value=r.requestNo||"";$("approvalNo").value=r.approvalNo||"";$("periodFrom").value=r.periodFrom||"";$("periodTo").value=r.periodTo||"";$("requestServices").value=r.services||"";$("requestReason").value=r.reason||"";$("requestRemarks").value=r.remarks||"";$("laborRows").replaceChildren();(r.labor||[]).forEach(addLabor);if(!r.labor?.length)addLabor();$("requestMaterialRows").replaceChildren();await projectChanged("regie",r.lvPosition);(r.materials||[]).forEach(addRequestMaterial);if(!r.materials?.length)addRequestMaterial();S.regieEvidence=structuredClone(r.evidence||[]);S.regieSignatures=structuredClone(r.signatures||{});renderEvidence("regie");renderSignatures("regie");$("deleteRegieBtn").hidden=!allowed("regieapp.requests.delete");$("regieEditorTitle").textContent=`Regieanforderung ${r.requestNo||""}`;saveState("regie",false);calcRequest();showView("regie-editor")}
 function addLabor(d={}){const row=node("div","priceRow laborRow"),hours=input(d.hours,"Std.","number"),cat=input(d.category,"Kategorie"),rate=input(d.rate,"EHP","number"),sum=node("b","moneyTotal",euro((d.hours||0)*(d.rate||0)));hours.step=rate.step="0.01";hours.oninput=rate.oninput=calcRequest;row.append(label("Std.",hours),label("Kategorie",cat),label("EHP",rate),label("Summe",sum),remove(row,calcRequest));$("laborRows").append(row)}
 function addRequestMaterial(d={}){const row=node("div","requestMaterialRow"),lvPicker=makeLvPicker(d.lvPosition,"regie"),lv=lvPicker.querySelector(".materialLv"),article=input(d.article,"Artikel"),q=input(d.quantity,"Menge","number"),unit=makeUnitPicker(d.unit),rate=input(d.rate,"EHP","number"),sum=node("b","moneyTotal",euro((d.quantity||0)*(d.rate||0)));article.className="materialArticle";q.className="materialQuantity";rate.className="materialRate";q.step=rate.step="0.01";q.oninput=rate.oninput=calcRequest;lv.onchange=()=>materialLvChanged(row,true);row.append(label("LV-Unterposition suchen oder frei eingeben",lvPicker),label("Artikel",article),label("Menge",q),label("Einheit",unit),label("EHP",rate),label("Summe",sum),remove(row,calcRequest));$("requestMaterialRows").append(row)}
 function calcRequest(){let total=0;document.querySelectorAll(".laborRow").forEach(r=>{const ins=r.querySelectorAll("input"),sum=(Number(ins[0].value)||0)*(Number(ins[2].value)||0);r.querySelector(".moneyTotal").textContent=euro(sum);total+=sum});document.querySelectorAll(".requestMaterialRow").forEach(r=>{const sum=(Number(r.querySelector(".materialQuantity").value)||0)*(Number(r.querySelector(".materialRate").value)||0);r.querySelector(".moneyTotal").textContent=euro(sum);total+=sum});$("requestTotal").textContent=euro(total)}
 function collectPriceRows(selector,isLabor){return [...document.querySelectorAll(selector)].map(r=>{if(isLabor){const i=r.querySelectorAll("input");return{hours:Number(i[0].value)||0,category:i[1].value.trim(),rate:Number(i[2].value)||0}}return{lvPosition:r.querySelector(".materialLv").value,article:r.querySelector(".materialArticle").value.trim(),quantity:Number(r.querySelector(".materialQuantity").value)||0,unit:getUnit(r),rate:Number(r.querySelector(".materialRate").value)||0}}).filter(x=>Object.values(x).some(Boolean))}
 async function saveRegie(e){e.preventDefault();if(!$("regieForm").reportValidity())return;const id=$("regieId").value||uid(),old=await RegieDB.get("reports",id),manual=$("regieProject").value===MANUAL_PROJECT,p=manual?null:project($("regieProject").value),b=branchForProject(p),manualProject=manual?collectManualProject("regie"):null,r={...old,id,type:"regie-request",projectId:p?.id||"",projectName:p?.name||manualProject?.name||old?.projectName||"",branchId:p?.branchId||"",costCenterName:manualProject?.costCenter||b?.name||"",requestNo:$("requestNo").value.trim(),approvalNo:$("approvalNo").value.trim(),lvPosition:$("regieLvPosition").value,periodFrom:$("periodFrom").value,periodTo:$("periodTo").value,services:$("requestServices").value.trim(),reason:$("requestReason").value.trim(),labor:collectPriceRows(".laborRow",true),materials:collectPriceRows(".requestMaterialRow",false),remarks:$("requestRemarks").value.trim(),evidence:structuredClone(S.regieEvidence),signatures:structuredClone(S.regieSignatures),manualProject,createdBy:old?.createdBy||S.user.id||"local-user",createdByName:old?.createdByName||[S.user.firstName,S.user.lastName].filter(Boolean).join(" ")||S.user.username||"Lokaler Benutzer",createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),syncStatus:manual?"local":"pending",conflict:old?.conflict||null};await RegieDB.put("reports",r);if(!manual)await RegieSync.queueReport(r);await reload();$("deleteRegieBtn").hidden=!allowed("regieapp.requests.delete");saveState("regie",false);toast(manual?"Regieanforderung lokal gespeichert":navigator.onLine?"Regieanforderung gespeichert – Synchronisierung läuft":"Regieanforderung sicher offline gespeichert")}
 async function deleteRegie(){const id=$("regieId").value,r=await RegieDB.get("reports",id);if(r&&confirm("Regieanforderung wirklich löschen?")){await RegieSync.queueDelete(r);await reload();showView("regie")}}function requestTotal(r){return (r.labor||[]).reduce((s,x)=>s+x.hours*x.rate,0)+(r.materials||[]).reduce((s,x)=>s+x.quantity*x.rate,0)}
 async function projectChanged(type,selected=""){const id=$(type==="work"?"workProject":"regieProject").value,manual=id===MANUAL_PROJECT,p=manual?null:project(id),b=branchForProject(p);showManualProject(type,manual);$(type==="work"?"workCostCenter":"regieCostCenter").value=b?`${b.code?`${b.code} · `:""}${b.name}`:manual?$(manualIds(type).costCenter).value:"";if(type==="work"&&p){$("workClient").value=p.customer||"";$("workOrderNo").value=p.customerOrderNumber||p.internalOrderNumber||p.number||""}const positions=manual?[]:await RegieLV.loadProject(id);fillLvSelect(type,positions,selected)}
 function fillLvSelect(type,positions,selected=""){const s=$(type==="work"?"workLvPosition":"regieLvPosition");s.replaceChildren(new Option("optional auswählen",""));positions.forEach(p=>s.add(new Option(`${p.pos} · ${p.text}`,p.pos)));if(selected&&!positions.some(p=>p.pos===selected))s.add(new Option(`${selected} · im Bericht gespeichert`,selected));s.value=selected||"";refreshMaterialLvSelects(type,positions)}
 function refreshMaterialLvSelects(type,positions){const selector=type==="work"?".workMaterialRow .lvMaterialPicker":".requestMaterialRow .lvMaterialPicker";document.querySelectorAll(selector).forEach(picker=>{const search=picker.querySelector(".materialLvSearch"),select=picker.querySelector(".materialLv");populateMaterialLvPicker(picker,positions,search.value,select.value)})}
 function lvSelected(type){const pos=$(type==="work"?"workLvPosition":"regieLvPosition").value,p=RegieLV.getPositions().find(x=>x.pos===pos);if(!p)return;const area=$(type==="work"?"workServices":"requestServices");if(!area.value.trim())area.value=`${p.pos} · ${p.text}`}
 function input(value="",placeholder="",type="text"){const i=document.createElement("input");i.type=type;i.value=value??"";i.placeholder=placeholder;return i}function label(t,child){const l=document.createElement("label");l.append(document.createTextNode(t),child);return l}function remove(row,after){const b=node("button","rowRemove","×");b.onclick=()=>{row.remove();after?.()};return b}
 function bindEvidence(type){const cap=$(type==="work"?"workCameraInput":"regieCameraInput"),gal=$(type==="work"?"workGalleryInput":"regieGalleryInput");$(type==="work"?"takeWorkPhotoBtn":"takeRegiePhotoBtn").onclick=()=>cap.click();$(type==="work"?"chooseWorkPhotoBtn":"chooseRegiePhotoBtn").onclick=()=>gal.click();$(type==="work"?"newWorkSketchBtn":"newRegieSketchBtn").onclick=()=>openDrawing({mode:"evidence",reportType:type,type:"sketch"});cap.onchange=e=>queuePhotos(type,[...(e.target.files||[])]);gal.onchange=e=>queuePhotos(type,[...(e.target.files||[])]);}
 async function queuePhotos(type,files){S.photoQueue=files.map(file=>({type,file}));await nextPhoto()}async function nextPhoto(){const q=S.photoQueue.shift();if(!q)return;const data=await fileData(q.file);openDrawing({mode:"evidence",reportType:q.type,type:"photo",name:q.file.name,background:data})}function fileData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
 function evidence(type){return type==="work"?S.workEvidence:S.regieEvidence}function setEvidence(type,value){if(type==="work")S.workEvidence=value;else S.regieEvidence=value}
 function renderEvidence(type){const box=$(type==="work"?"workEvidence":"regieEvidence"),items=evidence(type);box.replaceChildren();box.classList.toggle("emptyState",!items.length);if(!items.length){box.textContent="Noch keine Fotos oder Skizzen.";return}items.forEach(item=>{const card=node("article","evidenceItem"),img=document.createElement("img");img.src=item.preview;const meta=node("div","evidenceMeta"),category=document.createElement("select"),desc=input(item.description,"Bildbeschreibung");["Ausführung","Vorher","Nachher","Mangel","Skizze"].forEach(x=>category.add(new Option(x,x)));category.value=item.category|| (item.type==="sketch"?"Skizze":"Ausführung");category.onchange=()=>item.category=category.value;desc.oninput=()=>item.description=desc.value;meta.append(category,desc);const actions=node("div","evidenceActions"),edit=node("button","secondary","Markieren"),del=node("button","danger","Entfernen");edit.onclick=()=>openDrawing({mode:"evidence",reportType:type,evidenceId:item.id,type:item.type,name:item.name,document:item.drawing});del.onclick=async()=>{if(item.remoteAttachmentId){const report=await RegieDB.get("reports",$(type==="work"?"workId":"regieId").value);await RegieSync.queueAttachmentDelete(report,item.remoteAttachmentId)}setEvidence(type,items.filter(x=>x.id!==item.id));renderEvidence(type)};actions.append(edit,del);card.append(img,meta,actions);box.append(card)})}
 function bindSignatures(){[["signCompanyBtn","work","company"],["signCustomerBtn","work","customer"],["signSiteManagerBtn","regie","siteManager"],["signClientBtn","regie","client"],["signHasplBtn","regie","haspl"]].forEach(([id,t,key])=>$(id).onclick=()=>openDrawing({mode:"signature",reportType:t,key}))}
 function bindWorkServiceDrawing(){$("drawWorkServicesBtn").onclick=()=>openDrawing({mode:"service",reportType:"work",document:S.workServiceDrawing?.drawing});$("editWorkServicesDrawingBtn").onclick=()=>openDrawing({mode:"service",reportType:"work",document:S.workServiceDrawing?.drawing});$("removeWorkServicesDrawingBtn").onclick=removeWorkServiceDrawing}
 function renderWorkServiceDrawing(){const panel=$("workServiceDrawingPanel"),preview=$("workServiceDrawingPreview"),src=S.workServiceDrawing?.preview||"";panel.hidden=!src;if(src)preview.src=src;else preview.removeAttribute("src")}
 async function removeWorkServiceDrawing(){const old=S.workServiceDrawing;if(old?.remoteAttachmentId){const report=await RegieDB.get("reports",$("workId").value);await RegieSync.queueAttachmentDelete(report,old.remoteAttachmentId)}S.workServiceDrawing=null;renderWorkServiceDrawing();saveState("work",true)}
 function signatures(type){return type==="work"?S.workSignatures:S.regieSignatures}function renderSignatures(type){const map=type==="work"?{company:"companySignaturePreview",customer:"customerSignaturePreview"}:{siteManager:"siteManagerSignaturePreview",client:"clientSignaturePreview",haspl:"hasplSignaturePreview"};Object.entries(map).forEach(([k,id])=>{const img=$(id),src=RegieSync.signatureData(signatures(type)[k]);if(src)img.src=src;else img.removeAttribute("src")})}
 function bindDrawing(){S.drawing=new DrawingPad($("drawingCanvas"));$("drawingCancelBtn").onclick=()=>{$("drawingDialog").close();S.photoQueue=[]};$("drawingDoneBtn").onclick=drawingDone;$("drawingUndoBtn").onclick=()=>S.drawing.undo();$("drawingRedoBtn").onclick=()=>S.drawing.redo();$("drawingColor").oninput=e=>S.drawing.setColor(e.target.value);$("drawingWidth").onchange=e=>S.drawing.setWidth(e.target.value);$("drawingPaper").onchange=e=>S.drawing.setPaper(e.target.value);document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-tool]").forEach(x=>x.classList.toggle("active",x===b));S.drawing.setTool(b.dataset.tool)})}
 async function openDrawing(ctx){S.drawingContext=ctx;$("drawingTitle").textContent=ctx.mode==="signature"?"Unterschrift":ctx.mode==="service"?"Arbeitsleistung handschriftlich":ctx.type==="photo"?"Foto markieren":"Skizze";const paperMode=ctx.mode==="service"||ctx.mode==="evidence"&&ctx.type==="sketch";$("drawingTools").classList.toggle("signatureMode",ctx.mode==="signature");$("drawingTools").classList.toggle("serviceMode",ctx.mode==="service");$("drawingTools").classList.toggle("paperMode",paperMode);S.drawing.setExpandable(ctx.mode==="service");const doc=ctx.document||{background:ctx.background||null,paper:ctx.mode==="service"?"lined":"blank",objects:[]};if(ctx.mode==="service"&&!doc.paper)doc.paper="lined";if(paperMode&&!doc.paper)doc.paper="blank";$("drawingPaper").value=doc.paper||"blank";await S.drawing.reset(doc);$("drawingDialog").showModal();requestAnimationFrame(()=>S.drawing.resizeCss())}
 async function drawingDone(){const ctx=S.drawingContext,doc=S.drawing.document(),preview=S.drawing.preview({cropToContent:ctx.mode==="service"});if(ctx.mode==="service"){if(!preview){showWarning("Keine Handschrift erkannt","Bitte zuerst die Arbeitsleistung eintragen oder das Fenster mit Abbrechen schließen.");return}const old=S.workServiceDrawing;if(old?.remoteAttachmentId){const report=await RegieDB.get("reports",$("workId").value);await RegieSync.queueAttachmentDelete(report,old.remoteAttachmentId)}S.workServiceDrawing={drawing:doc,preview,attachmentId:uid(),remoteAttachmentId:null};renderWorkServiceDrawing();saveState("work",true)}else if(ctx.mode==="signature"){const old=signatures(ctx.reportType)[ctx.key];if(typeof old==="object"&&old.remoteAttachmentId){const report=await RegieDB.get("reports",$(ctx.reportType==="work"?"workId":"regieId").value);await RegieSync.queueAttachmentDelete(report,old.remoteAttachmentId)}signatures(ctx.reportType)[ctx.key]={dataUrl:preview,attachmentId:uid()};renderSignatures(ctx.reportType)}else{const arr=evidence(ctx.reportType),existing=arr.find(x=>x.id===ctx.evidenceId);if(existing?.remoteAttachmentId){const report=await RegieDB.get("reports",$(ctx.reportType==="work"?"workId":"regieId").value);await RegieSync.queueAttachmentDelete(report,existing.remoteAttachmentId)}const item={id:existing?.id||uid(),type:ctx.type||existing?.type||"sketch",name:ctx.name||existing?.name||`Skizze ${arr.length+1}`,category:existing?.category||(ctx.type==="sketch"?"Skizze":"Ausführung"),description:existing?.description||"",createdAt:existing?.createdAt||new Date().toISOString(),drawing:doc,preview,attachmentId:uid(),remoteAttachmentId:null};if(existing)Object.assign(existing,item);else arr.push(item);renderEvidence(ctx.reportType)}$("drawingDialog").close();if(S.photoQueue.length)setTimeout(nextPhoto,150)}
 function allowed(key){return !HasplAuth.isProtected()||S.user.role==="admin"||S.user.role==="development"||S.user.featurePermissions?.[key]===true}
 function applyPermissions(){const set=(ids,key)=>ids.forEach(id=>{const el=$(id);if(el)el.hidden=!allowed(key)});set(["newWorkBtn","workAddBtn"],"regieapp.work_reports.create");set(["newRegieBtn","regieAddBtn"],"regieapp.requests.create");set(["printWorkBtn"],"regieapp.work_reports.export");set(["printRegieBtn"],"regieapp.requests.export");set(["signCompanyBtn","signCustomerBtn"],"regieapp.work_reports.sign");set(["lvFile","importLvBtn","deleteLvBtn"],"regieapp.lv.import");$("workSaveBtn").hidden=!(allowed("regieapp.work_reports.create")||allowed("regieapp.work_reports.edit"));$("regieSaveBtn").hidden=!(allowed("regieapp.requests.create")||allowed("regieapp.requests.edit"))}
 async function printCurrent(type){const id=$(type==="work"?"workId":"regieId").value,report=(type==="work"?S.work:S.regie).find(r=>r.id===id);if(!report){toast("Bitte den Bericht zuerst speichern");return}const key=type==="work"?"regieapp.work_reports.export":"regieapp.requests.export";if(!allowed(key)){toast("Keine Berechtigung für den Export");return}try{await RegiePrint.print(report,S.master);toast("PDF wurde erstellt")}catch(error){console.error(error);toast("PDF konnte nicht erstellt werden")}}
 function showConflict(report){const server=report.conflict?.server||{};$("conflictDialog").dataset.reportId=report.id;$("conflictTitle").textContent=`Konflikt: ${report.type==="work"?"Arbeitsbericht":"Regieanforderung"} ${report.reportNo||report.requestNo||""}`;$("conflictText").textContent=`Server-Revision ${server.revision||report.conflict?.serverRevision||"?"}, geändert ${server.updatedAt||server.updated_at||report.conflict?.serverUpdatedAt||"unbekannt"}. Bitte bewusst auswählen, welche Version erhalten bleiben soll.`;$("conflictDetails").textContent=JSON.stringify(server,null,2);$("conflictDialog").showModal()}
 async function resolveCurrentConflict(mode){const id=$("conflictDialog").dataset.reportId;if(await RegieSync.resolveConflict(id,mode)){ $("conflictDialog").close();await reload();toast(mode==="server"?"Server-Version übernommen":"Lokale Version zur Synchronisierung vorgemerkt")}}
 function showUser(){const name=[S.user.firstName,S.user.lastName].filter(Boolean).join(" ")||S.user.username||"Lokaler Benutzer";const ks=S.master.branches?.find(b=>b.id===S.user.branchId);$("userDetails").textContent=`${name}${S.user.role?` · Rolle: ${S.user.role}`:""}${ks?` · Kostenstelle: ${ks.name}`:""}`;$("userDialog").showModal()}
 async function registerSW(){if("serviceWorker" in navigator)try{const r=await navigator.serviceWorker.register("./service-worker.js");r.update().catch(()=>{})}catch(e){console.warn(e)}}
 init().catch(e=>{console.error(e);toast("RegieApp konnte nicht vollständig gestartet werden")});
})();
