(function(){
 "use strict";
 const S={projectId:"",fileName:"",sheetRows:{},sheetNames:[],detection:null,positions:[],saved:[]};
 const $=id=>document.getElementById(id);
 const text=v=>String(v??"").trim();
 const norm=v=>text(v).toLowerCase().replace(/ä/g,"a").replace(/ö/g,"o").replace(/ü/g,"u").replace(/ß/g,"ss").replace(/[^a-z0-9]+/g," ").trim();
 const number=v=>{if(typeof v==="number")return Number.isFinite(v)?v:0;let s=text(v).replace(/[€$%A-Za-z]/g,"").replace(/\s/g,"").replace(/'/g,"");if(s.includes(",")&&s.includes(".")){s=s.lastIndexOf(",")>s.lastIndexOf(".")?s.replace(/\./g,"").replace(",","."):s.replace(/,/g,"")}else if(s.includes(","))s=s.replace(/\./g,"").replace(",",".");const n=Number(s);return Number.isFinite(n)?n:0};
 const money=v=>new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR"}).format(Number(v)||0);
 const qty=v=>new Intl.NumberFormat("de-AT",{maximumFractionDigits:3}).format(Number(v)||0);
 const TERMS={pos:["position","pos","pos nr","lgposnr","positionsnummer"],text:["positionsstichwort","positionstext","kurztext","leistung","bezeichnung","leistungsbeschreibung"],qty:["lv menge","menge","ausschreibungsmenge","vertragsmenge"],unit:["eh","einheit","mengeneinheit"],labor:["lohn","lohn eh","lohnanteil"],material:["sonstiges","sonst eh","material","material eh"],ep:["eh preis","ep","einheitspreis","preis eh"],lg:["lg","leistungsgruppe"]};
 function headerMap(row){const map={},scores={};Object.entries(TERMS).forEach(([field,terms])=>{let best=-1,bscore=0;(row||[]).forEach((v,i)=>{const n=norm(v);let score=0;for(const t of terms){if(n===t)score=Math.max(score,10);else if(n.startsWith(t+" "))score=Math.max(score,8);else if(n.includes(t))score=Math.max(score,5)}if(field==="pos"&&n.includes("stichwort"))score=0;if(score>bscore){bscore=score;best=i}});if(best>=0){map[field]=best;scores[field]=bscore}});let score=Object.values(scores).reduce((a,b)=>a+b,0);if(map.pos!=null)score+=12;if(map.text!=null)score+=12;return{map,score}}
 function detect(){let best=null;for(const [sheetName,rows] of Object.entries(S.sheetRows)){const bonus=/lv.?uber|lv.?übers|leistungsverzeichnis|kollaudierung/i.test(sheetName)?35:0;for(let r=0;r<Math.min(rows.length,80);r++){const h=headerMap(rows[r]),score=h.score+bonus;if(!best||score>best.score)best={sheetName,headerRow:r,map:h.map,score}}}return best&&best.score>20?best:null}
 function colName(i){let n=i+1,s="";while(n){const r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26)}return s}
 function populate(sheetName,headerRow,preset={}){const rows=S.sheetRows[sheetName]||[],header=rows[headerRow]||[],max=Math.max(header.length,...rows.slice(headerRow,headerRow+8).map(r=>r.length),1),options=[new Option("– nicht zuordnen –","")];for(let i=0;i<max;i++)options.push(new Option(`${colName(i)} · ${text(header[i])||"(ohne Überschrift)"}`,String(i)));const ids={pos:"mapPos",text:"mapText",qty:"mapQty",unit:"mapUnit",labor:"mapLabor",material:"mapMaterial",ep:"mapEP",lg:"mapLG"};Object.entries(ids).forEach(([field,id])=>{const node=$(id);node.replaceChildren(...options.map(o=>o.cloneNode(true)));node.value=preset[field]!=null?String(preset[field]):""});preview()}
 function mapping(){const get=id=>$(id).value===""?null:Number($(id).value);return{pos:get("mapPos"),text:get("mapText"),qty:get("mapQty"),unit:get("mapUnit"),labor:get("mapLabor"),material:get("mapMaterial"),ep:get("mapEP"),lg:get("mapLG")}}
 function parsed(limit=null){
  const rows=S.sheetRows[$("lvSheet").value]||[],start=Math.max(0,(Number($("lvHeaderRow").value)||1)-1),m=mapping(),out=[],seen=new Set();
  if(m.pos==null||m.text==null)return out;
  for(let r=start+1;r<rows.length;r++){
   const a=rows[r]||[],pos=text(a[m.pos]).replace(/\s+/g,""),description=text(a[m.text]);
   if(!pos||!description||/^(summe|gesamt|übertrag|uebertrag)$/i.test(description)||seen.has(pos))continue;
   const qtyRaw=m.qty!=null?text(a[m.qty]):"",unit=m.unit!=null?text(a[m.unit]):"",laborRaw=m.labor!=null?text(a[m.labor]):"",materialRaw=m.material!=null?text(a[m.material]):"",epRaw=m.ep!=null?text(a[m.ep]):"";
   if(m.qty!=null&&m.unit!=null&&!qtyRaw&&!unit&&!laborRaw&&!materialRaw&&!epRaw)continue;
   const labor=number(laborRaw),material=number(materialRaw);let ep=number(epRaw);if(!ep&&(labor||material))ep=labor+material;
   out.push({pos,text:description,lv_qty:number(qtyRaw),unit,labor,material,ep,lg:m.lg!=null?text(a[m.lg]):(pos.match(/^(\d{2})/)?.[1]||"")});seen.add(pos);
   if(limit&&out.length>=limit)break;
  }
  return out;
 }
 function preview(){if($("lvMappingCard").hidden)return;const rows=parsed(),sample=rows.slice(0,30);$("lvPreviewCount").textContent=rows.length?`${rows.length} LV-Unterpositionen erkannt.`:"Position und Positionstext zuordnen.";$("importLvBtn").disabled=!rows.length;$("lvPreview").innerHTML=sample.length?table(sample):"<div class='emptyState'>Keine gültige Vorschau.</div>"}
 function table(rows){return `<table><thead><tr><th>LG</th><th>Pos.</th><th>Leistung</th><th>LV-Menge</th><th>EH</th><th>Lohn/EH</th><th>Sonst./EH</th><th>EP</th></tr></thead><tbody>${rows.map(p=>`<tr><td>${escapeHtml(p.lg)}</td><td><b>${escapeHtml(p.pos)}</b></td><td>${escapeHtml(p.text)}</td><td class="num">${qty(p.lv_qty)}</td><td>${escapeHtml(p.unit)}</td><td class="num">${money(p.labor)}</td><td class="num">${money(p.material)}</td><td class="num">${money(p.ep)}</td></tr>`).join("")}</tbody></table>`}
 function escapeHtml(v){const d=document.createElement("div");d.textContent=text(v);return d.innerHTML}
 function parseXml(source){return new DOMParser().parseFromString(source,"application/xml")}
 function columnIndex(ref){const letters=String(ref||"").match(/^[A-Z]+/i)?.[0]?.toUpperCase()||"A";let n=0;for(const c of letters)n=n*26+c.charCodeAt(0)-64;return n-1}
 async function readXlsx(file){
  if(typeof JSZip==="undefined")throw new Error("Lokales Excel-Modul fehlt.");
  const zip=await JSZip.loadAsync(await file.arrayBuffer()),read=async path=>{const item=zip.file(path);return item?item.async("string"):""};
  const workbook=parseXml(await read("xl/workbook.xml")),rels=parseXml(await read("xl/_rels/workbook.xml.rels")),relMap={};
  [...rels.getElementsByTagName("Relationship")].forEach(r=>relMap[r.getAttribute("Id")]=r.getAttribute("Target"));
  const sharedXml=await read("xl/sharedStrings.xml"),shared=sharedXml?[...parseXml(sharedXml).getElementsByTagName("si")].map(si=>[...si.getElementsByTagName("t")].map(t=>t.textContent).join("")):[];
  S.sheetRows={};S.sheetNames=[];
  for(const sheet of workbook.getElementsByTagName("sheet")){
   const name=sheet.getAttribute("name")||"Tabelle",target=relMap[sheet.getAttribute("r:id")];if(!target)continue;
   const path=target.startsWith("/")?target.slice(1):"xl/"+target.replace(/^\.\//,"");const xml=parseXml(await read(path)),rows=[];
   for(const rowNode of xml.getElementsByTagName("row")){
    const row=[];for(const cell of rowNode.getElementsByTagName("c")){const ix=columnIndex(cell.getAttribute("r")),type=cell.getAttribute("t"),v=cell.getElementsByTagName("v")[0]?.textContent??"";let value=v;if(type==="s")value=shared[Number(v)]??"";else if(type==="inlineStr")value=[...cell.getElementsByTagName("t")].map(t=>t.textContent).join("");else if(type==="b")value=v==="1"?"WAHR":"FALSCH";row[ix]=value}rows.push(row.map(v=>v??""));
   }S.sheetNames.push(name);S.sheetRows[name]=rows;
  }
 }
 function readCsv(source){const delimiter=(source.split(/\r?\n/,1)[0].match(/;/g)||[]).length>(source.split(/\r?\n/,1)[0].match(/,/g)||[]).length?";":",",rows=[];let row=[],cell="",quoted=false;for(let i=0;i<source.length;i++){const c=source[i];if(c==='"'){if(quoted&&source[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===delimiter&&!quoted){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&source[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell=""}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
 async function excel(file){const low=file.name.toLowerCase();if(low.endsWith(".csv")){S.sheetRows={CSV:readCsv(await file.text())};S.sheetNames=["CSV"]}else await readXlsx(file);S.detection=detect()}
 async function pdf(file){const pdfjs=await import("../assets/pdf.min.mjs");pdfjs.GlobalWorkerOptions.workerSrc=new URL("assets/pdf.worker.min.mjs",location.href).href;const doc=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,pages=[];let itemsCount=0;for(let pn=1;pn<=doc.numPages;pn++){const page=await doc.getPage(pn),tc=await page.getTextContent(),vp=page.getViewport({scale:1}),items=tc.items.map(it=>({text:text(it.str),x:Number(it.transform?.[4]||0),y:Number(it.transform?.[5]||0),w:Number(it.width||0)})).filter(i=>i.text);itemsCount+=items.length;pages.push({page:pn,width:vp.width,lines:groupLines(items)})}if(itemsCount<8)throw new Error("Diese PDF enthält keinen zuverlässig auslesbaren Text. OCR wäre erforderlich.");const positions=parsePdf(pages);if(!positions.length)throw new Error("Keine unterstützte LV-Tabelle erkannt. Bitte Zuordnung in der KollApp prüfen oder Excel verwenden.");S.sheetRows={"PDF-Erkennung":[["LG","Position","Positionstext","LV-Menge","EH","Lohn / EH","Sonstiges / EH","EH-Preis"],...positions.map(p=>[p.lg,p.pos,p.text,p.lv_qty,p.unit,p.labor,p.material,p.ep])]};S.sheetNames=["PDF-Erkennung"];S.detection={sheetName:"PDF-Erkennung",headerRow:0,map:{lg:0,pos:1,text:2,qty:3,unit:4,labor:5,material:6,ep:7},score:100}}
 function groupLines(items){const sorted=items.slice().sort((a,b)=>b.y-a.y||a.x-b.x),lines=[];for(const it of sorted){let l=lines.find(x=>Math.abs(x.y-it.y)<=3.2);if(!l){l={y:it.y,items:[]};lines.push(l)}l.items.push(it)}lines.forEach(l=>l.items.sort((a,b)=>a.x-b.x));return lines.sort((a,b)=>b.y-a.y)}
 function lineText(l){return l.items.map(i=>i.text).join(" ").replace(/\s+/g," ").trim()}
 function joinZone(line,min,max){return line.items.filter(i=>i.x>=min&&i.x<max).map(i=>i.text).join(" ").replace(/\s+/g," ").trim()}
 function kwpCode(v){const x=text(v).replace(/\s+/g,"");return /^\d{6}[A-Za-z0-9]{0,3}$/.test(x)?x:""}
 function parseKwp(pages){const out=[],seen=new Set();for(const pg of pages){const hi=pg.lines.findIndex(l=>{const n=norm(lineText(l));return n.includes("lgposnr")&&n.includes("positionsstichwort")&&n.includes("an menge")&&n.includes("eh")});if(hi<0)continue;const k=(Number(pg.width)||792)/792,z={lg:[34,50],pos:[50,91],text:[105,254],qty:[254,285],unit:[314,331],rvLabor:[331,355],rvMaterial:[355,379],idxLabor:[405,429],idxMaterial:[429,453]},zone=(l,key)=>joinZone(l,z[key][0]*k,z[key][1]*k);let last=null;for(let i=hi+1;i<pg.lines.length;i++){const l=pg.lines[i],whole=norm(lineText(l));if(whole.startsWith("gesamtsumme")||whole.includes("zu beachten anmerkungen"))break;const pos=kwpCode(zone(l,"pos")),desc=zone(l,"text");if(pos&&desc){const idxL=zone(l,"idxLabor"),idxM=zone(l,"idxMaterial"),use=/\d/.test(idxL+idxM),labor=number(use?idxL:zone(l,"rvLabor")),material=number(use?idxM:zone(l,"rvMaterial"));const row={lg:zone(l,"lg")||(pos.match(/^(\d{2})/)?.[1]||""),pos,text:desc,lv_qty:number(zone(l,"qty")),unit:zone(l,"unit"),labor,material,ep:labor+material};if(!seen.has(pos)){out.push(row);seen.add(pos);last=row}}else if(last&&desc&&!zone(l,"qty")&&!zone(l,"unit"))last.text=(last.text+" "+desc).trim()}}return out}
 function parseGeneric(pages){const out=[],seen=new Set();let anchors=null;for(const pg of pages){let hi=-1;for(let i=0;i<pg.lines.length;i++){const l=pg.lines[i],n=norm(lineText(l));if(n.includes("position")&&/(positionsstichwort|positionstext|leistung)/.test(n)){anchors={};l.items.forEach(it=>{const h=norm(it.text);if(/lgposnr|pos nr|position/.test(h)&&anchors.pos==null)anchors.pos=it.x;else if(/stichwort|text|leistung/.test(h)&&anchors.text==null)anchors.text=it.x;else if(/menge/.test(h)&&anchors.qty==null)anchors.qty=it.x;else if((h==="eh"||h.includes("einheit"))&&anchors.unit==null)anchors.unit=it.x});hi=i;break}}if(!anchors?.pos||!anchors?.text)continue;const fields=Object.keys(anchors).sort((a,b)=>anchors[a]-anchors[b]),bounds=fields.slice(0,-1).map((f,i)=>(anchors[f]+anchors[fields[i+1]])/2);for(let i=hi+1;i<pg.lines.length;i++){const c={};for(const it of pg.lines[i].items){let ix=0;while(ix<bounds.length&&it.x>=bounds[ix])ix++;const f=fields[ix];c[f]=(c[f]?c[f]+" ":"")+it.text}const pos=text(c.pos).replace(/\s/g,""),desc=text(c.text);if(pos.length>=4&&/[0-9]/.test(pos)&&desc&&!seen.has(pos)){out.push({lg:pos.match(/^(\d{2})/)?.[1]||"",pos,text:desc,lv_qty:number(c.qty),unit:text(c.unit),labor:0,material:0,ep:0});seen.add(pos)}}}return out}
 function parsePdf(pages){const kwp=parseKwp(pages);return kwp.length?kwp:parseGeneric(pages)}
 async function fileChanged(){const file=$("lvFile").files?.[0];if(!file)return;S.fileName=file.name;$("lvImportInfo").className="importInfo";$("lvImportInfo").textContent=`${file.name} wird lokal analysiert …`;try{file.name.toLowerCase().endsWith(".pdf")?await pdf(file):await excel(file);const d=S.detection||{sheetName:S.sheetNames[0],headerRow:0,map:{}};$("lvSheet").replaceChildren(...S.sheetNames.map(n=>new Option(n,n)));$("lvSheet").value=d.sheetName;$("lvHeaderRow").value=d.headerRow+1;$("lvMappingCard").hidden=false;populate(d.sheetName,d.headerRow,d.map);$("lvImportInfo").className="importInfo success";$("lvImportInfo").textContent=`${file.name}: ${parsed().length} LV-Unterpositionen erkannt. Zuordnung bitte prüfen.`}catch(error){$("lvMappingCard").hidden=true;$("lvImportInfo").className="importInfo error";$("lvImportInfo").textContent=error.message}}
 async function importLv(){const projectId=$("lvProject").value,positions=parsed();if(!projectId){alert("Bitte zuerst eine Baustelle wählen.");return}if(!positions.length)return;const record={projectId,sourceFile:S.fileName,importedAt:new Date().toISOString(),positions,syncStatus:"pending"};await RegieDB.masterPut("lv:"+projectId,record);await RegieSync.queueLv(projectId,record);S.saved=positions;renderSaved();window.dispatchEvent(new CustomEvent("regie-lv-updated",{detail:{projectId,positions}}));alert(`${positions.length} LV-Unterpositionen wurden lokal gespeichert.${navigator.onLine?" Die Synchronisierung mit dem Portal läuft.":" Sie werden später automatisch synchronisiert."}`)}
 function reportUsesLv(report){return !!(text(report.lvPosition)||(report.materials||[]).some(row=>text(row.lvPosition)))}
 async function openDeleteLv(){
  if(!S.projectId||!S.saved.length)return;
  if(HasplAuth.isProtected()&&!RegieSync.can("regieapp.lv.import")){alert("Keine Berechtigung zum Entfernen des Leistungsverzeichnisses.");return}
  const reports=(await RegieDB.getAll("reports")).filter(report=>!report.deletedAt&&report.projectId===S.projectId),used=reports.filter(reportUsesLv),references=used.reduce((count,report)=>count+(text(report.lvPosition)?1:0)+(report.materials||[]).filter(row=>text(row.lvPosition)).length,0),projectName=$("lvProject").selectedOptions?.[0]?.textContent||S.projectId;
  $("deleteLvDialog").dataset.projectId=S.projectId;$("deleteLvProjectText").textContent=`Baustelle: ${projectName} · ${S.saved.length} gespeicherte LV-Positionen.`;
  $("deleteLvUsageText").textContent=used.length?`${used.length} gespeicherte${used.length===1?"r Bericht verwendet":" Berichte verwenden"} insgesamt ${references} LV-Zuordnung${references===1?"":"en"}. Diese Zuordnungen bleiben als Bestandteil der Berichte gespeichert.`:"Kein gespeicherter Bericht verwendet derzeit eine LV-Zuordnung. Auch alle anderen Berichtsdaten bleiben unverändert.";
  $("deleteLvConfirmBtn").disabled=false;$("deleteLvConfirmBtn").textContent="LV endgültig entfernen";$("deleteLvDialog").showModal();
 }
 async function confirmDeleteLv(){
  const projectId=$("deleteLvDialog").dataset.projectId;if(!projectId||projectId!==S.projectId){$("deleteLvDialog").close();return}
  const button=$("deleteLvConfirmBtn");button.disabled=true;button.textContent="LV wird entfernt …";
  try{
   const now=new Date().toISOString(),record={projectId,sourceFile:"",importedAt:now,deletedAt:now,positions:[],syncStatus:"pending"};
   await RegieDB.masterPut("lv:"+projectId,record);await RegieSync.queueLv(projectId,record);S.saved=[];renderSaved();window.dispatchEvent(new CustomEvent("regie-lv-updated",{detail:{projectId,positions:[]}}));
   $("deleteLvDialog").close();$("lvImportInfo").className="importInfo success";$("lvImportInfo").textContent=navigator.onLine?"Das LV wurde lokal entfernt. Die Löschung im Portal wird synchronisiert.":"Das LV wurde lokal entfernt. Die Löschung im Portal erfolgt automatisch, sobald wieder eine Verbindung besteht.";
  }catch(error){button.disabled=false;button.textContent="LV endgültig entfernen";$("deleteLvUsageText").textContent=`Das LV konnte nicht entfernt werden: ${error.message||"Unbekannter Fehler"}`}
 }
 async function loadProject(projectId){S.projectId=projectId;let record=projectId?await RegieDB.masterGet("lv:"+projectId):null;S.saved=record?.positions||[];renderSaved();if(projectId&&navigator.onLine){const remote=await RegieSync.pullLv(projectId);if(remote&&S.projectId===projectId){record=remote;S.saved=record.positions||[];renderSaved();window.dispatchEvent(new CustomEvent("regie-lv-updated",{detail:{projectId,positions:S.saved}}))}}return S.saved}
 function renderSaved(){const q=norm($("lvSearch")?.value),rows=S.saved.filter(p=>!q||norm(p.pos+" "+p.text).includes(q)),canRemove=!HasplAuth.isProtected()||RegieSync.can("regieapp.lv.import");$("savedLvCount").textContent=`${S.saved.length} Positionen`;$("deleteLvBtn").hidden=!S.projectId||!S.saved.length||!canRemove;$("savedLvTable").classList.toggle("emptyState",!rows.length);$("savedLvTable").innerHTML=rows.length?table(rows):(S.projectId?"Für diese Baustelle ist noch kein LV gespeichert.":"Bitte zuerst eine Baustelle wählen.")}
 function init(){$("lvFile").addEventListener("change",fileChanged);$("lvProject").addEventListener("change",e=>loadProject(e.target.value));$("lvSheet").addEventListener("change",()=>{const rows=S.sheetRows[$("lvSheet").value]||[],best={headerRow:0,map:{},score:-1};rows.slice(0,80).forEach((r,i)=>{const h=headerMap(r);if(h.score>best.score)Object.assign(best,{headerRow:i,map:h.map,score:h.score})});$("lvHeaderRow").value=best.headerRow+1;populate($("lvSheet").value,best.headerRow,best.map)});$("lvHeaderRow").addEventListener("change",()=>{const r=Math.max(0,Number($("lvHeaderRow").value)-1),h=headerMap(S.sheetRows[$("lvSheet").value]?.[r]||[]);populate($("lvSheet").value,r,h.map)});["mapPos","mapText","mapQty","mapUnit","mapLabor","mapMaterial","mapEP","mapLG"].forEach(id=>$(id).addEventListener("change",preview));$("importLvBtn").addEventListener("click",importLv);$("lvSearch").addEventListener("input",renderSaved);$("deleteLvBtn").addEventListener("click",openDeleteLv);$("deleteLvCancelBtn").addEventListener("click",()=>$("deleteLvDialog").close());$("deleteLvConfirmBtn").addEventListener("click",confirmDeleteLv)}
 window.RegieLV=Object.freeze({init,loadProject,getPositions:()=>S.saved.slice()});
})();
